# self_assessment_questions.py

import random
from typing import Dict, List


QUESTION_BANK: Dict[str, List[str]] = {
    "emotional_awareness": ["I understand my strengths clearly.",
"I am aware of my weaknesses.",
"I reflect on my emotions regularly.",
"I recognize how my emotions affect my behavior.",
"I understand what motivates me.",
"I am aware of my core values.",
"I know what situations trigger stress in me.",
"I recognize patterns in my thoughts.",
"I understand my emotional reactions.",
"I am conscious of my decision-making style.",
"I know what makes me feel fulfilled.",
"I am aware of my personal boundaries.",
"I recognize when I need help.",
"I understand my learning style.",
"I can identify my dominant personality traits.",
"I reflect on my mistakes.",
"I understand how past experiences shape me.",
"I recognize my emotional strengths.",
"I am aware of my emotional limits.",
"I understand my priorities in life.",
"I can identify my fears.",
"I know what situations energize me.",
"I understand my communication style.",
"I recognize when I feel overwhelmed.",
"I am aware of my personal goals.",
"I understand my reactions under pressure.",
"I reflect on my daily behavior.",
"I know what makes me anxious.",
"I recognize when I am emotionally exhausted.",
"I understand my coping mechanisms.",
"I am aware of my habitual thought patterns.",
"I recognize when I need rest.",
"I understand how I handle criticism.",
"I am aware of my emotional triggers.",
"I understand my self-image.",
"I reflect on my interpersonal relationships.",
"I recognize my emotional needs.",
"I understand my comfort zones.",
"I am aware of my growth areas.",
"I recognize how I respond to failure.",
"I understand my personal beliefs.",
"I am aware of my decision biases.",
"I recognize my behavioral habits.",
"I understand my emotional responses to success.",
"I reflect on my daily choices.",
"I know what situations reduce my confidence.",
"I recognize my internal dialogue.",
"I understand my reaction to change.",
"I am aware of my stress patterns.",
"I understand my emotional priorities.",
"I recognize my strengths under pressure.",
"I understand my limitations realistically.",
"I reflect on my role in conflicts.",
"I recognize my emotional resilience.",
"I understand my long-term aspirations.",
"I am aware of my emotional balance.",
"I recognize when I need emotional support.",
"I understand my adaptability.",
"I reflect on my mental habits.",
"I understand how I process feedback.",
"I recognize my emotional responses to uncertainty.",
"I understand my sense of identity.",
"I am aware of my inner motivations.",
"I reflect on how I handle responsibility.",
"I recognize my mental strengths.",
"I understand how I react to expectations.",
"I am aware of my emotional growth.",
"I recognize my self-reflection patterns.",
"I understand my emotional awareness.",
"I reflect on my personal development.",
"I recognize my reactions to success.",
"I understand my emotional regulation capacity.",
"I am aware of my internal conflicts.",
"I recognize my self-evaluation habits.",
"I understand how I perceive myself.",
"I reflect on my emotional clarity.",
"I recognize my awareness of others’ emotions.",
"I understand my emotional intelligence level.",
"I am aware of my self-confidence sources.",
"I recognize my emotional maturity.",
"I understand my emotional self-control.",
"I reflect on my internal decision processes.",
"I recognize my emotional awareness growth.",
"I understand my emotional adaptability.",
"I am aware of my self-awareness development.",
"I recognize how I learn from experiences.",
"I understand my emotional insight.",
"I reflect on my mental clarity.",
"I recognize my emotional honesty.",
"I understand my internal emotional balance.",
"I am aware of my personal insight.",
"I recognize my self-reflection depth.",
"I understand my emotional comprehension.",
"I reflect on my awareness improvements.",
"I recognize my emotional learning.",
"I understand my awareness of self-change.",
"I am aware of my internal awareness.",
"I recognize my emotional mindfulness.",
"I understand my self-perception accuracy.",
"I reflect regularly on who I am becoming.",
    ],

    "self_confidence": ["I can calm myself when stressed.",
"I manage my emotions effectively.",
"I stay composed during challenges.",
"I regulate my anger appropriately.",
"I handle disappointment constructively.",
"I manage anxiety effectively.",
"I control impulsive reactions.",
"I remain emotionally stable under pressure.",
"I can pause before reacting emotionally.",
"I manage frustration well.",
"I cope with emotional setbacks.",
"I regulate emotional intensity.",
"I recover quickly from emotional stress.",
"I manage emotional overwhelm.",
"I handle emotional conflict calmly.",
"I regulate negative emotions.",
"I stay emotionally balanced.",
"I manage emotional responses to criticism.",
"I regulate emotions during uncertainty.",
"I manage emotional reactions in social situations.",
"I stay calm during disagreements.",
"I regulate emotions during exams or deadlines.",
"I manage emotional exhaustion.",
"I regulate stress effectively.",
"I handle emotional pressure well.",
"I regulate mood fluctuations.",
"I manage emotional triggers.",
"I remain calm in unexpected situations.",
"I regulate emotions when feeling judged.",
"I manage emotional discomfort.",
"I regulate emotional tension.",
"I handle emotional setbacks maturely.",
"I manage emotional reactions to failure.",
"I regulate emotional responses to success.",
"I maintain emotional composure.",
"I regulate emotional reactions in groups.",
"I manage emotional reactions to feedback.",
"I regulate emotional frustration.",
"I manage emotional reactions to change.",
"I regulate emotional reactions to uncertainty.",
"I manage emotional disappointment.",
"I regulate emotional distress.",
"I manage emotional pressure from expectations.",
"I regulate emotional responses to conflict.",
"I manage emotional overload.",
"I regulate emotional stress.",
"I manage emotional reactions thoughtfully.",
"I regulate emotional balance.",
"I manage emotional turbulence.",
"I regulate emotional discomfort calmly.",
"I manage emotional reactions to setbacks.",
"I regulate emotional intensity effectively.",
"I manage emotional tension productively.",
"I regulate emotional responses mindfully.",
"I manage emotional challenges.",
"I regulate emotional frustration constructively.",
"I manage emotional reactions to disappointment.",
"I regulate emotional awareness during stress.",
"I manage emotional responses intentionally.",
"I regulate emotional responses consciously.",
"I manage emotional reactions responsibly.",
"I regulate emotional impulses.",
"I manage emotional energy effectively.",
"I regulate emotional responses to pressure.",
"I manage emotional fatigue.",
"I regulate emotional clarity.",
"I manage emotional resilience.",
"I regulate emotional self-control.",
"I manage emotional recovery.",
"I regulate emotional steadiness.",
"I manage emotional reactions to stressors.",
"I regulate emotional responses under pressure.",
"I manage emotional awareness.",
"I regulate emotional regulation skills.",
"I manage emotional calmness.",
"I regulate emotional responses adaptively.",
"I manage emotional strain.",
"I regulate emotional consistency.",
"I manage emotional reactions thoughtfully.",
"I regulate emotional composure.",
"I manage emotional stability.",
"I regulate emotional reactions calmly.",
"I manage emotional self-regulation.",
"I regulate emotional mindfulness.",
"I manage emotional equilibrium.",
"I regulate emotional reactions constructively.",
"I manage emotional self-discipline.",
"I regulate emotional reactions effectively.",
"I manage emotional control.",
"I regulate emotional resilience.",
"I manage emotional stress wisely.",
"I regulate emotional responses intentionally.",
"I manage emotional reactions healthily.",
"I regulate emotional reactions responsibly.",
"I manage emotional balance effectively.",
"I regulate emotional calmness.",
"I manage emotional composure under stress.",
"I regulate emotional strength.",
"I manage emotional self-management.",
"I regulate emotional wellbeing.",

    ],

    "growth_mindset": [
       "I feel motivated to achieve my goals.",
"I set clear personal goals.",
"I stay committed to my objectives.",
"I feel driven to improve myself.",
"I persist despite challenges.",
"I work consistently toward my goals.",
"I feel motivated to learn new skills.",
"I stay focused on long-term goals.",
"I am self-driven.",
"I take initiative toward my goals.",
"I maintain motivation over time.",
"I feel inspired to grow.",
"I pursue goals with determination.",
"I stay motivated even when progress is slow.",
"I set meaningful goals.",
"I feel energized by my ambitions.",
"I pursue self-improvement actively.",
"I stay motivated during setbacks.",
"I track progress toward goals.",
"I feel motivated by challenges.",
"I commit to personal development.",
"I stay goal-focused under pressure.",
"I feel motivated to overcome obstacles.",
"I take responsibility for my goals.",
"I maintain clarity about my goals.",
"I feel purpose-driven.",
"I stay motivated without external pressure.",
"I pursue excellence.",
"I feel motivated by personal growth.",
"I maintain discipline toward goals.",
"I stay focused on priorities.",
"I feel motivated to complete tasks.",
"I pursue meaningful achievements.",
"I stay motivated despite distractions.",
"I set achievable goals.",
"I feel motivated to challenge myself.",
"I commit to my aspirations.",
"I stay motivated during uncertainty.",
"I pursue goals strategically.",
"I feel driven by purpose.",
"I maintain motivation in routine tasks.",
"I feel motivated to succeed.",
"I stay focused on self-improvement.",
"I pursue growth intentionally.",
"I feel motivated to take action.",
"I maintain motivation through difficulties.",
"I stay committed to personal goals.",
"I feel motivated by progress.",
"I pursue long-term vision.",
"I stay motivated in academic goals.",
"I feel motivated to reach milestones.",
"I maintain persistence.",
"I stay focused on future outcomes.",
"I feel motivated to overcome failures.",
"I pursue continuous improvement.",
"I stay motivated in challenging situations.",
"I feel driven to accomplish goals.",
"I maintain motivation through feedback.",
"I stay goal-oriented consistently.",
"I feel motivated to achieve excellence.",
"I pursue meaningful challenges.",
"I stay motivated by learning.",
"I feel motivated by personal standards.",
"I maintain motivation under stress.",
"I pursue goals proactively.",
"I stay motivated despite fatigue.",
"I feel driven by self-growth.",
"I maintain clarity of purpose.",
"I stay motivated to improve skills.",
"I pursue goals with resilience.",
"I feel motivated to push limits.",
"I maintain focus on objectives.",
"I stay motivated despite obstacles.",
"I pursue goals with passion.",
"I feel motivated by achievement.",
"I maintain motivation consistently.",
"I stay goal-oriented daily.",
"I feel motivated to progress.",
"I pursue goals with commitment.",
"I maintain motivation over challenges.",
"I stay focused on growth.",
"I feel motivated by self-achievement.",
"I pursue goals deliberately.",
"I maintain motivation through effort.",
"I stay motivated through setbacks.",
"I feel driven by ambition.",
"I pursue goals persistently.",
"I maintain motivation through discipline.",
"I stay motivated to complete goals.",
"I feel motivated to excel.",
"I pursue purposeful goals.",
"I maintain motivation through self-belief.",
"I stay goal-focused consistently.",
"I feel motivated to advance.",
"I pursue goals strategically.",
"I maintain motivation during challenges.",
"I stay motivated to achieve targets.",
"I feel driven to reach goals.",
"I pursue continuous goal growth.",
"I maintain strong motivation levels.",

    ],

    "social_wellbeing": [
        "I communicate clearly with others.",
"I listen actively.",
"I express my thoughts effectively.",
"I respect others’ opinions.",
"I handle conflicts constructively.",
"I empathize with others.",
"I build positive relationships.",
"I collaborate well in teams.",
"I express emotions appropriately.",
"I maintain healthy boundaries.",
"I resolve disagreements calmly.",
"I communicate assertively.",
"I adapt communication styles.",
"I value teamwork.",
"I manage interpersonal conflicts.",
"I express feedback respectfully.",
"I understand others’ emotions.",
"I maintain professional relationships.",
"I collaborate effectively.",
"I handle social pressure.",
"I engage in constructive dialogue.",
"I communicate needs clearly.",
"I show empathy consistently.",
"I maintain respectful interactions.",
"I manage group dynamics.",
"I build trust with others.",
"I handle misunderstandings well.",
"I express appreciation.",
"I communicate assertively but kindly.",
"I adapt to social situations.",
"I resolve conflicts peacefully.",
"I listen without interrupting.",
"I understand social cues.",
"I communicate with confidence.",
"I handle criticism maturely.",
"I express disagreement respectfully.",
"I maintain positive interactions.",
"I engage actively in discussions.",
"I collaborate toward shared goals.",
"I support others emotionally.",
"I communicate clearly under stress.",
"I show patience in conversations.",
"I handle interpersonal stress.",
"I respect differences.",
"I manage difficult conversations.",
"I communicate honestly.",
"I build rapport easily.",
"I handle social anxiety.",
"I maintain cooperation.",
"I express empathy in conflict.",
"I communicate expectations clearly.",
"I engage constructively with peers.",
"I respect boundaries.",
"I handle disagreements thoughtfully.",
"I collaborate effectively in groups.",
"I listen empathetically.",
"I communicate openly.",
"I handle social feedback.",
"I manage relationship challenges.",
"I build meaningful connections.",
"I communicate respectfully.",
"I handle group discussions well.",
"I engage positively with others.",
"I manage social responsibilities.",
"I resolve interpersonal issues.",
"I communicate assertively when needed.",
"I express emotions constructively.",
"I handle interpersonal tension.",
"I support teamwork.",
"I maintain clear communication.",
"I engage socially with confidence.",
"I manage peer interactions.",
"I respect emotional differences.",
"I handle social conflict calmly.",
"I communicate effectively in groups.",
"I build cooperative relationships.",
"I handle interpersonal stress wisely.",
"I express empathy consistently.",
"I communicate constructively.",
"I manage social expectations.",
"I build supportive relationships.",
"I communicate effectively across differences.",
"I handle relationship feedback.",
"I engage respectfully in debates.",
"I maintain positive social behavior.",
"I manage interpersonal challenges.",
"I communicate needs assertively.",
"I show understanding toward others.",
"I handle social situations gracefully.",
"I maintain strong interpersonal skills.",
"I communicate clearly and calmly.",
"I build trust in relationships.",
"I handle social responsibilities effectively.",
"I engage empathetically with peers.",
"I communicate constructively in conflicts.",
"I manage social relationships well.",
"I express empathy openly.",
"I communicate respectfully under pressure.",
"I handle interpersonal interactions thoughtfully.",
"I maintain healthy social relationships.",

    ],

"stress_coping": [
    "I maintain emotional wellbeing.",
"I manage stress healthily.",
"I recover from setbacks.",
"I maintain mental balance.",
"I practice self-care.",
"I manage emotional exhaustion.",
"I stay resilient under pressure.",
"I prioritize wellbeing.",
"I cope with stress effectively.",
"I maintain psychological wellbeing.",
"I recover quickly from challenges.",
"I manage mental fatigue.",
"I practice healthy coping strategies.",
"I maintain emotional resilience.",
"I handle stress constructively.",
"I maintain positive mental health.",
"I adapt to difficult situations.",
"I practice stress management.",
"I recover emotionally from stress.",
"I maintain inner balance.",
"I manage pressure effectively.",
"I practice mindfulness.",
"I handle adversity well.",
"I maintain wellbeing under stress.",
"I cope with uncertainty.",
"I manage emotional strain.",
"I maintain mental clarity.",
"I practice emotional self-care.",
"I handle emotional challenges.",
"I maintain resilience.",
"I manage psychological stress.",
"I recover from emotional setbacks.",
"I practice healthy routines.",
"I maintain mental stability.",
"I cope with pressure positively.",
"I manage wellbeing proactively.",
"I maintain emotional health.",
"I handle emotional fatigue.",
"I practice resilience strategies.",
"I maintain psychological balance.",
"I cope with emotional challenges.",
"I manage stress thoughtfully.",
"I maintain wellbeing habits.",
"I recover from mental strain.",
"I.practice stress reduction.",
"I maintain emotional wellbeing consistently.",
"I cope with emotional difficulties.",
"I manage wellbeing intentionally.",
"I maintain mental resilience.",
"I handle stress adaptively.",
"I practice emotional balance.",
"I maintain wellbeing awareness.",
"I cope with stressors effectively.",
"I manage mental challenges.",
"I maintain psychological strength.",
"I practice self-compassion.",
"I recover from stress quickly.",
"I maintain wellbeing under pressure.",
"I cope with emotional stress.",
"I manage psychological wellbeing.",
"I maintain emotional strength.",
"I practice wellbeing strategies.",
"I cope with mental challenges.",
"I manage emotional wellbeing.",
"I maintain resilience under stress.",
"I practice mental self-care.",
"I recover from emotional fatigue.",
"I maintain wellbeing balance.",
"I cope with pressure healthily.",
"I manage emotional resilience.",
"I practice emotional regulation.",
"I maintain mental wellness.",
"I cope with emotional strain.",
"I manage wellbeing stress.",
"I maintain psychological resilience.",
"I practice wellbeing routines.",
"I cope with emotional adversity.",
"I manage stress resilience.",
"I maintain emotional health proactively.",
"I practice mental wellbeing.",
"I cope with stress constructively.",
"I manage emotional wellness.",
"I maintain resilience consistently.",
"I practice self-care intentionally.",
"I cope with mental fatigue.",
"I manage wellbeing effectively.",
"I maintain emotional resilience habits.",
"I.practice stress resilience.",
"I cope with emotional pressure.",
"I manage psychological resilience.",
"I maintain wellbeing awareness daily.",
"I cope with emotional challenges positively.",
"I manage mental wellbeing actively.",
"I maintain emotional stability.",
"I practice resilience daily.",
"I cope with psychological stress.",
"I manage wellbeing intentionally.",
"I maintain emotional wellness.",
"I practice mental resilience.",
"I cope with stress healthily.",

]
}

def generate_assessment_questions(
    questions_per_domain: int = 5,
    seed: str | None = None
) -> Dict[str, List[str]]:
    """
    Randomly select N questions from each domain.
    If seed is provided, selection becomes reproducible.
    """

    if seed:
        random.seed(seed)

    selected = {}

    for domain, questions in QUESTION_BANK.items():
        if len(questions) < questions_per_domain:
            raise ValueError(
                f"Not enough questions in domain '{domain}'. "
                f"Required: {questions_per_domain}, Found: {len(questions)}"
            )

        selected[domain] = random.sample(questions, questions_per_domain)

    return selected


def flatten_questions(selected_questions: Dict[str, List[str]]) -> List[dict]:
    """
    Convert domain-wise questions into a flat list
    for step-by-step rendering.
    """

    flat = []

    for domain, questions in selected_questions.items():
        for q in questions:
            flat.append({
                "domain": domain,
                "question": q
            })

    return flat